# Generated by Django 6.0 on 2025-12-28 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='deciption',
            new_name='description',
        ),
    ]
